name: larastan

on: 
  workflow_call:
    inputs:
      php:
        description: 'The PHP version'
        default: '8.2'
        required: false
        type: string

jobs:
  larastan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          coverage: none
        env:
          GITHUB_TOKEN: "${{ secrets.AGICOM_TOKEN }}"

      - name: Remove local dependencies
        run: composer config repositories.local --unset

      - name: Install PHP dependencies
        run: composer install --no-interaction --no-progress --ansi

      - name: Execute Static Analysis Tool
        run: ./vendor/bin/phpstan analyse --ansi
